env:
  - VERSION=1.0.0
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev libcrypto++-dev
language: cpp
compiler:
  - gcc
script: 
  - qmake CONFIG+=release CONFIG+=local
  - make
  - make install INSTALL_ROOT=./release
#   - tar -C ./release/ -cvjf Qtz-$VERSION-release.tar.bz2 ./usr