env:
  - VERSION=1.0.0
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqt4-dev libcrypto++-dev
language: cpp
compiler:
  - gcc
script: 
  - qmake CONFIG+=release CONFIG+=local DEFINES+=PRIVATE_KEY=\\\\\\\"f9bf8a579d1fa38c4e20ee884e4096c054b57771153799f49fb674d1006caf52\\\\\\\"
  - make
  - make install INSTALL_ROOT=./release
#   - tar -C ./release/ -cvjf Qtz-$VERSION-release.tar.bz2 ./usr